% % Release mode.
% mex -I../include/ ...
%     -I../../csm/include/ ...
%     -I/opt/ros/indigo/include ...
%     -I/usr/include/eigen3 -I/usr/include ...
%     -L../../../../../../devel/lib ...
%     -lcsm_processor.so ...
%     -l:/usr/lib/libgtsam.so.2.3.1 ...
%     -lboost_system ...
%     mex_csm_caller.cpp ...
%     -v

% Debug mode.
mex -I/home/prasanna/catkin_ws/src/bnr_workspace/thesis/multi_robot_CFS/csm_processor/include/ ...
    -I/home/prasanna/catkin_ws/src/bnr_workspace/thesis/multi_robot_CFS/csm/include/ ...
    -I/opt/ros/indigo/include ...
    -I/usr/include/eigen3 -I/usr/include ...
    -L/home/prasanna/catkin_ws/devel/lib ...
    -lcsm_processor.so ...
    -l:/usr/local/lib/libgtsamDebug.so.4.0.0 ...
    mex_csm_caller.cpp ...
    -v -g
