% % Release mode.
% mex -I../include/ ...
%     -I../../csm/include/ ...
%     -I/opt/ros/indigo/include ...
%     -I/usr/include/eigen3 -I/usr/include ...
%     -L../../../../../../devel/lib ...
%     -lcsm_processor.so ...
%     -l:/usr/lib/libgtsam.so.2.3.1 ...
%     -lboost_system ...
%     mex_csm_caller.cpp ...
%     -v

% Debug mode.
mex -I../include/ ...
    -I../../csm/include/ ...
    -I/opt/ros/indigo/include ...
    -I/usr/include/eigen3 -I/usr/include ...
    -L../../../../../../devel/lib ...
    -lcsm_processor.so ...
    -l:/usr/lib/libgtsam.so.2.3.1 ...
    -lboost_system ...
    mex_csm_caller.cpp ...
    -v -g
