function lmap_factor = gen_lmap_factors(robot_id, var_1, var_2, pose_1, pose_2, del_t)

import gtsam.*

global lmap_covariance_per_time_ratio key_offset;

% LMAP CONSTRAINTS
%       Using lmap data
[del_lmap_x, del_lmap_y, del_lmap_theta] = odometry_difference(pose_1(1), ...
                                                               pose_1(2), ...
                                                               pose_1(3), ...
                                                               pose_2(1), ...
                                                               pose_2(2), ...
                                                               pose_2(3));
% Delta time scaled Odometry Dead Reckoning covariance. 
lmap_noise = noiseModel.Diagonal.Sigmas([lmap_covariance_per_time_ratio(1); ...
                                         lmap_covariance_per_time_ratio(5); ...
                                         lmap_covariance_per_time_ratio(9)] * (del_t^2));
%         Adding odometry contraints to graph
offset_var_1 = robot_id * key_offset(robot_id) + var_1;
offset_var_2 = robot_id * key_offset(robot_id) + var_2;
lmap_factor = BetweenFactorPose2(offset_var_1, offset_var_2, Pose2(del_lmap_x, del_lmap_y, del_lmap_theta), lmap_noise);
